-- 데이터베이스 선택
USE DB2025Team04;

-- 1. 뷰 제거
DROP VIEW IF EXISTS VIEW_USER_RENT_STATUS;
DROP VIEW IF EXISTS VIEW_USER_RENTAL_OVERVIEW;

-- 기존 데이터 삭제 (나중에 지워야 함)
DELETE FROM DB2025_RENT;
DELETE FROM DB2025_RESERVATION;


-- 2. 테이블 제거 (자식 → 부모 순서)
DROP TABLE IF EXISTS DB2025_OVERDUES; -- (나중에 지워야 함)
DROP TABLE IF EXISTS DB2025_RESERVATION;
DROP TABLE IF EXISTS DB2025_RENT;
DROP TABLE IF EXISTS DB2025_ADMIN;
DROP TABLE IF EXISTS DB2025_ITEMS;
DROP TABLE IF EXISTS DB2025_USER;
DROP TABLE IF EXISTS DB2025_RENT_LOG;
