-- 데이터베이스 선택
USE DB2025Team04;

-- 1. 뷰 제거
DROP VIEW IF EXISTS VIEW_USER_RENTAL_OVERVIEW;
DROP VIEW IF EXISTS VIEW_RESERVATION_OVERVIEW;
DROP VIEW IF EXISTS VIEW_RENTAL_ITEMS_STATUS;

-- 2. 테이블 제거 (자식 → 부모 순서)
DROP TABLE IF EXISTS DB2025_OVERDUES; -- 최종적으로는 사용하지 않지만, 이전 버전에서 사용되었을 수 있음
DROP TABLE IF EXISTS DB2025_RESERVATION;
DROP TABLE IF EXISTS DB2025_RENT;
DROP TABLE IF EXISTS DB2025_ADMIN;
DROP TABLE IF EXISTS DB2025_ITEMS;
DROP TABLE IF EXISTS DB2025_USER;
DROP TABLE IF EXISTS DB2025_RENT_LOG;
