-- 데이터베이스 선택
USE DB2025Team04;

-- 1. 뷰 제거
DROP VIEW IF EXISTS VIEW_USER_RENTAL_OVERVIEW;
DROP VIEW IF EXISTS VIEW_RESERVATION_OVERVIEW;
DROP VIEW IF EXISTS VIEW_RENTAL_ITEMS_STATUS;

-- 2. 인덱스 제거 (MySQL에서는 인덱스를 테이블 단위로 제거)
DROP INDEX IF EXISTS idx_rent_status ON DB2025_RENT;
DROP INDEX IF EXISTS idx_overdue_user_id ON DB2025_OVERDUES;
DROP INDEX IF EXISTS idx_item_category ON DB2025_ITEMS;
DROP INDEX IF EXISTS idx_overdues_user_item_restriction ON DB2025_OVERDUES;
DROP INDEX IF EXISTS idx_rent_user_status_due ON DB2025_RENT;

-- 3. 테이블 제거 (자식 → 부모 순서)
DROP TABLE IF EXISTS DB2025_OVERDUES;
DROP TABLE IF EXISTS DB2025_RESERVATION;
DROP TABLE IF EXISTS DB2025_RENT;
DROP TABLE IF EXISTS DB2025_ADMIN;
DROP TABLE IF EXISTS DB2025_ITEMS;
DROP TABLE IF EXISTS DB2025_USER;
